---
services:
  kometa-filme:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-filme
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/filme:/config
    restart: no
  kometa-filme-4k:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-filme-4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/filme-4k:/config
    restart: no
  kometa-filme-archive:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-filme-archive
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/filme-archive:/config
    restart: no
  kometa-serien:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-serien
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/serien:/config
    restart: no
  kometa-serien-4k:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-serien-4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/serien-4k:/config
    restart: no
  kometa-serien-archiv:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa-serien-archiv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config/serien-archiv:/config
    restart: no