---
services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=03:00 #optional
      - KOMETA_RUN=True #optional
    env_file:
      - ./kometa.env
    volumes:
      - ./config:/config
    restart: unless-stopped